### ISSUE TITLE
Hover function not working

### ISSUE THREAD

**Issue by Felix-Braun** [IBM/zopeneditor-about#322]
**Development environment**

- Z Open Editor version: 3.0.1
- Editor Platform
  - Visual Studio Code
- Editor Platform Version: 1.75.1
- Operating System: Windows 10 (10.0.19044)
- Java Version: openjdk version "11.0.3-redhat" 2019-04-16 LTS
- Zowe CLI version: 7.10.4
- Zowe Explorer version: 2.6.1
- Node.js version: 18.12.0

**Problem Description**

The Problem is, that the Hover- and  go to declaration Function doesn't always work. We thought that it could be related to the size of the program.
If the Declaration hover function doesn't work, neither does the peek definition , go to definition, find all references and jump to sections. Opening Copys or Includes works, but not from a Variable, only from the copy/include it self. The preview doesn't work either.

**Comment by sdaimwood** [comment]
Hi Felix, in the documents where the functionality is lost are there any errors present? As documented in https://github.com/IBM/zopeneditor-about/issues/300, this is a known issue with the COBOL parser where errors will cause language features to be disabled as the document is considered invalid and a full parse cannot complete.

**Comment by paulobigas** [comment]
Hello. I confirm that I have the same problem. If a copybook declared in a program have a ERRO_TOKEN problem (already identified in other issues) the hover and peek stops working.

**Comment by Felix-Braun** [comment]
Hello, but why does it only say **"ERROR_TOKEN" unexpected tokens ignored** when I have the copy in front of a Variable declaration, but when i move it above another copy it says: **Copybook 'I9PTEPOS' contains the following error: "." expected after this token** but when I open the copybook, there are no errors or problems showing

**Comment by sdaimwood** [comment]
Hi @Felix-Braun , we've seen that error most commonly in situations related to #313, where there are large copybooks being downloaded via z/OSMF. Is that the case for your environment?

**Comment by phaumer** [comment]
@Felix-Braun @paulobigas thanks for reporting these. After discussion we believe that these will also be fixed with the fix for #300. So closing it as a dup for now. I will ping you when a fix is available in a comment for #300.

**Comment by phaumer** [comment]
@Felix-Braun @paulobigas please trying the new v3.1.0 and let us know if this fixes your issue.

**Comment by Felix-Braun** [comment]
Hello, I can't test it, because it can't find any of the copybooks, not those stored locally and not those in the changeman libaries. Do I have do modify the zapp.yaml file?

**Comment by Felix-Braun** [comment]
@phaumer I tried to modify the zapp.yaml file to version 3.1.0 but still doesn't find any of the copybooks.
in zapp.yaml
`version: 3.1.0`

**Comment by paulobigas** [comment]
@phaumer In my case I confirmed that it is working properly! The Error_Token error disappeared in all of my copybooks, and the hoovering is working as expected. Many thanks for you work.

**Comment by Felix-Braun** [comment]
Other people updated the extension and for them, it works fine and everythings works. but in my case it's unable to locate any of the copybook. I checked the property groups and all seems fine, I have no idea why it wouldn work

**Comment by paulobigas** [comment]
@Felix-Braun please check #320 . The zapp.yaml file must be in the root of the workspace directory. That was my problem.

**Comment by Felix-Braun** [comment]
found the proble, in the user settings.json file, I had     "zopeneditor.enforceCaseSensitiveIncludeFileNames": true, this was the error,

**Comment by phaumer** [comment]
Glad to hear that it worked for you. We are trying to convey as much troubleshooting info as we can in the logs. Let us know how we can improve.
