### ISSUE TITLE
Z Open Editor in State of Disfunction

### ISSUE THREAD

**Issue by davidkcoblentz** [IBM/zopeneditor-about#455]
## Development environment used

- Z Open Editor version:
- Version: 1.94.2 (user setup)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

- Editor Platform
  - Visual Studio Code

- Editor Platform Version:
OS: Windows_NT x64 10.0.19045

- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):
C:\Users\953053>java --version
java 11.0.19 2023-04-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.19+9-LTS-224)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.19+9-LTS-224, mixed mode)

  - Node.js version: None
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): no
- Tried turning on Zopen Editor logging but it does not appear in the drop down of the OUTPUT tab.
![image](https://github.com/user-attachments/assets/3416672e-9e8e-4e01-ab34-4b02af6381e2)

## VS Code/ZOpenEditor run state of disfunction
I have been using ZOpen Editor for years now but recently it halfway stopped working. It was functioning until now it seems like only part of the language server is functioning. It began this behavior recently when I accidentally fumbled in my typing and hit several keys on the keyboard but at the same (possibly including CTRL+SHIFT and maybe ALT plus others) time and am not sure what exactly what combination of keys I hit. I noticed the issue when I went to add a tab in a COBOL source by pressing the tab key and got the below error message. The first screen shot below shows what the editor shows now. Parts of it look normal but for example the COBOL Outline View that is normally populated is blank instead. I can add, edit and delete statements with the keyboard and use special editing key combinations like SHIFT+ALT down arrow to replicate a line. But no outline and cannot insert a tab for example. Hovering over a data name does not work and syntax highlighting a misspelled reserved work like 'MOVE' doesn't work. F12 doesn't work, etc... I am not sure how I managed to get into this state. 
I tried disabling ZOpen Editor and re-enabling but nothing changed.
I tried using the ZOE command to stop the language server but said it could not.
I realize the next step may be to uninstall and re-install, but I wanted to give you a chance to debug if you are interested to try and understand how it got into this state.

![image](https://github.com/user-attachments/assets/1b8dbf05-f53d-4e1c-a4c7-abea63e330aa)

![image](https://github.com/user-attachments/assets/3296f1a6-3ed4-4936-91a1-3aa899bc8f8d)

![image](https://github.com/user-attachments/assets/0cd6e25d-e23d-4081-aeff-12a180f86be1)

Detailed steps for reproducing the problem:

1. Impossible to know

### Observed behavior
- Can not input a tab in COBOL source code 
- COBOL outline view is blank
- No syntax checking for errors, misspelled words.
- F12 nor SHIFT+F12 does nothing
- Editing COBOL text works fine

### Expected behavior
- to be able to edit normally with ZOE

**Comment by FALLAI-Denis** [comment]
Hi @davidkcoblentz,

You don’t give information about ZOE version. 

For our part we use 4.x.x and 5.xx ZOE versions, (and 2.x.x and 3.x.x Zowe Explorer versions), and we don’t have this problem.
By past we experience some problems on ZOE commands, wich were solved by a « reload window ». 

I see you have a Java 11 version. 
ZOE 5.x.x require a Java 17 version. 

Perhaps you have a conflict problem between extensions. 
Do you try do deactivate or uninstall recently added extensions ?

Regards.

**Comment by phaumer** [comment]
Hello @davidkcoblentz. Also see here for an overview to the breaking changes with 5.0.0: https://ibm.github.io/zopeneditor-about/Blog/new-content.html 

If you require Java 11 you need to switch back to Z Open Editor 4.5.1 with Zowe Explorer 2.18. We still have the old download zips for those versions here as well: https://ibm.github.io/mainframe-downloads/downloads.html

**Comment by davidkcoblentz** [comment]
## Java Version
I downloaded Java 23 and installed it and uninstalled Java 11. I changed my JAVA HOME path to point to the new version 23 from 11. They had notes on Java 17 saying it may not have the latest security updates so I chose to try Java 23.

## Z Open Editor and Zowe Explorer
I uninstalled Z Open Editor and then Zowe Explorer extensions. I re-installing Z Open Editor after I installed and configured Java 23. I realize Z Open Editor also installs Zowe Explorer. My current Zowe Explorer version that installed with the latest Z Open Editor is:

![image](https://github.com/user-attachments/assets/e3a6b128-b52c-43f7-8e09-256deb052957)

I am still waiting for AA tech support to install and configure OSMF on our mainframe so I can use Zowe Explorer eventually but have never used it so far. But, I had setup a Zowe profile a long time ago and get the following message when I start VS Code with Z Open Editor installed. I have tried both buttons to CONVERT the profile and to attempt to setup a new one but I get no dialog after clicking either button. I have searched VS Code Zowe Explorer settings to find the profile to update it or delete. I tried Command 'Zowe Explorer: Delete a Profile Permanently' but get the below message. I am still trying to delete or update the old profile.

![image](https://github.com/user-attachments/assets/94caa4a9-3b8b-482e-bb2c-4cbbd66b4f79)

![image](https://github.com/user-attachments/assets/483a0352-2adb-4176-b03a-21d67e7e3108)

**Comment by davidkcoblentz** [comment]
I did find the problem. I disabled several extensions and Z Open Editor began to work. I am checking to see which one is causing the issue.

## How do I delete my Zowe Explorer V1 profile or replace it with a new one?

**Comment by davidkcoblentz** [comment]
Get this message when trying to 'Change Zowe Profiles':

![image](https://github.com/user-attachments/assets/86d560af-10a8-4953-a23c-22c46f18d6ca)

**Comment by davidkcoblentz** [comment]
## Zowe Explorer log output:

Zowe Explorer 3.0.2
This log file can be found at c:\Users\953053\.vscode\extensions\zowe.vscode-extension-for-zowe-3.0.2
Zowe Explorer log level: INFO
[2024/10/29 12:10:08] [INFO] Zowe home directory is located at C:\Users\953053\.zowe
[2024/10/29 12:10:08] [INFO] No custom credential managers found, using the default instead.
[2024/10/29 12:10:08] [INFO] Zowe Profiles initialized successfully.
[2024/10/29 12:10:08] [INFO] No custom credential managers found, using the default instead.
[2024/10/29 12:10:08] [WARN] Zowe V1 profiles in use.
Zowe Explorer no longer supports V1 profiles. Choose to convert existing profiles to a team configuration or create new profiles.
[2024/10/29 12:10:10] [INFO] Convert v1 profiles to team configuration chosen.
[2024/10/29 12:10:10] [INFO] No custom credential managers found, using the default instead.
[2024/10/29 12:10:10] [INFO] 
[2024/10/29 12:10:10] [INFO] No custom credential managers found, using the default instead.

**Comment by phaumer** [comment]
My apologies we should test more for users without any Zowe profile requirements.

I assume you do not have Zowe CLI installed either then, because if you keep v7 of the CLI around it will create folders for you that cause those profile migration prompts. CLI v7 must be upgraded to v8.

If you do not use Zowe Explorer profiles you should be able to follow these steps to clean up:

- exit VS Code
- delete the entire .zowe folder in your home directory
- start VS Code with Z Open Editor 5 and Zowe Explorer 3
- it will show "No Zowe CLI profile found" in the lower right-hand corner, but you should be ready to go
- it has recreated that .zowe folder with only the latest files

Zowe Explorer will still prompt you to create profile in a dialog. You could ignore that or if you want to avoid the prompt for the future:

- click the "Create New" button
- click in the prompt at the top "Create a new Team Configuration File"
- click "Global"
- it will generate a default file
-  just close it would changing it

Next time you start there should be no more prompts. The status bar shows "rse (rse)" which is that unused default profile your created.

**Comment by davidkcoblentz** [comment]
Thanks for all of your help! Everything is working now. No Zowe profile prompt. Continuing to love using Z Open Editor!
just a Note: I am using Java v23 and all is working well. Thanks again!

**Comment by FALLAI-Denis** [comment]
Hi @davidkcoblentz,

You say you are waiting for z/OSMF setup on your mainframe partition and can’t use Zowe Explorer, (so I understand you don’t use RSEd). 

Do you try to install and use IBM z/OS FTP for Zowe Explorer extension?
This extension is an extender to base Zowe Explorer and use z/OS FTP server as an alternative to z/OSMS. 

Regards.

**Comment by FALLAI-Denis** [comment]
Hi @davidkcoblentz,

As an alternative to use personnal Zowe profiles, you can also use team Zowe profiles, and also project team Zowe profiles.

Project team Zowe profiles is our choice to avoid each developer to define profiles (wich they don’t manage well). Project team Zowe profiles files are stored at root level of ours Git repositories and so available to developers using these Git repositories. 

See https://github.com/zowe/zowe-cli/blob/master/docs/How_config_files_are_merged.md 

Regards
